const tarotDeck=[

    {name:"바보 (The Fool)",img:"https://upload.wikimedia.org/wikipedia/commons/c/c0/The_Fool_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"새로운 시작, 순수한 도전정신, 자유로운 모험",advice:"계획보다 행동이 앞서도 괜찮은 때이니, 두려워말고 첫 발을 내디뎌보세요.",luck:5},
    {name:"마법사 (The Magician)",img:"https://upload.wikimedia.org/wikipedia/commons/5/57/The_Magician_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"강한 의지와 창조력으로 원하는 것을 실현하는 힘",advice:"필요한 능력은 이미 갖추고 있으니, 지금 바로 실행에 옮기면 좋은 결과를 얻을 것입니다.",luck:5},
    {name:"여사제 (The High Priestess)",img:"https://upload.wikimedia.org/wikipedia/commons/0/0d/The_High_Priestess_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"직관과 내면의 지혜, 아직 드러나지 않은 비밀",advice:"논리보다 직감을 믿고 조용히 때를 기다리는 편이 유리합니다.",luck:3},
    {name:"여황제 (The Empress)",img:"https://upload.wikimedia.org/wikipedia/commons/f/fb/The_Empress_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"풍요와 창조, 넘치는 사랑과 다산",advice:"스스로를 돌보고 주변과 나누면 자연스럽게 풍요가 따라올 것입니다.",luck:5},
    {name:"황제 (The Emperor)",img:"https://upload.wikimedia.org/wikipedia/commons/f/f8/The_Emperor_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"안정적인 권위, 질서, 강한 리더십",advice:"원칙을 세우고 흔들림 없이 밀고 나가면 안정을 얻을 수 있습니다.",luck:4},
    {name:"교황 (The Hierophant)",img:"https://upload.wikimedia.org/wikipedia/commons/f/fe/The_Hierophant_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"전통과 가르침, 신뢰할 수 있는 조언",advice:"검증된 방법과 조언을 따르는 것이 지금은 가장 안전한 선택입니다.",luck:3},
    {name:"연인 (The Lovers)",img:"https://upload.wikimedia.org/wikipedia/commons/1/1b/The_Lovers_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"사랑과 조화로운 관계, 중요한 선택의 순간",advice:"마음이 이끄는 쪽을 선택하되, 그 선택에 책임을 지세요.",luck:5},
    {name:"전차 (The Chariot)",img:"https://upload.wikimedia.org/wikipedia/commons/8/88/The_Chariot_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"강한 의지로 밀어붙여 얻는 승리와 전진",advice:"여러 방향으로 흩어진 힘을 하나로 모으면 목표에 빠르게 도달합니다.",luck:4},
    {name:"힘 (Strength)",img:"https://upload.wikimedia.org/wikipedia/commons/7/74/Strength_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"부드러움으로 다스리는 진정한 용기와 인내",advice:"부딪히기보다 부드럽게 다가가면 어려운 상황도 풀립니다.",luck:4},
    {name:"은둔자 (The Hermit)",img:"https://upload.wikimedia.org/wikipedia/commons/1/1a/The_Hermit_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"홀로 성찰하며 답을 찾는 시간",advice:"잠시 혼자만의 시간을 가지면 지금 찾던 답이 보일 것입니다.",luck:3},
    {name:"운명의 수레바퀴 (Wheel of Fortune)",img:"https://upload.wikimedia.org/wikipedia/commons/0/03/Wheel_of_Fortune_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"변화의 흐름, 예상치 못한 좋은 전환점",advice:"흐름이 곧 바뀌니, 지금의 상황에 너무 연연하지 마세요.",luck:5},
    {name:"정의 (Justice)",img:"https://upload.wikimedia.org/wikipedia/commons/8/85/Justice_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"공정한 판단과 균형, 인과의 결과",advice:"원칙대로 행동하면 결국 정당한 결과를 얻게 됩니다.",luck:3},
    {name:"매달린 사람 (The Hanged Man)",img:"https://upload.wikimedia.org/wikipedia/commons/8/8e/The_Hanged_Man_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"잠시 멈추고 새로운 시각으로 바라보기",advice:"억지로 애쓰기보다 관점을 바꿔 기다리는 것이 답입니다.",luck:2},
    {name:"죽음 (Death)",img:"https://upload.wikimedia.org/wikipedia/commons/d/d3/Death_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"하나의 끝이자 새로운 시작으로의 전환",advice:"붙잡고 있던 것을 놓아야 새로운 국면이 열립니다.",luck:2},
    {name:"절제 (Temperance)",img:"https://upload.wikimedia.org/wikipedia/commons/6/66/Temperance_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"균형과 조화, 서두르지 않는 인내",advice:"서두르지 않고 조율하면 균형 잡힌 결과를 얻습니다.",luck:3},
    {name:"악마 (The Devil)",img:"https://upload.wikimedia.org/wikipedia/commons/b/b5/The_Devil_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"집착과 유혹, 스스로를 옭아매는 굴레",advice:"스스로를 옭아매고 있는 습관이나 관계를 돌아볼 때입니다.",luck:2},
    {name:"탑 (The Tower)",img:"https://upload.wikimedia.org/wikipedia/commons/8/8c/The_Tower_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"갑작스러운 붕괴와 충격적인 깨달음",advice:"예상치 못한 변화가 오더라도, 그것이 결국 더 단단한 기반을 만들어줍니다.",luck:1},
    {name:"별 (The Star)",img:"https://upload.wikimedia.org/wikipedia/commons/0/09/The_Star_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"희망과 치유, 밝은 미래에 대한 믿음",advice:"지금의 노력은 반드시 좋은 결실로 이어질 테니 희망을 잃지 마세요.",luck:5},
    {name:"달 (The Moon)",img:"https://upload.wikimedia.org/wikipedia/commons/1/18/The_Moon_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"불안과 혼란, 감춰진 진실에 대한 막연한 두려움",advice:"불확실함 속에서 성급한 결정은 피하고 상황이 명확해질 때까지 기다리세요.",luck:2},
    {name:"태양 (The Sun)",img:"https://upload.wikimedia.org/wikipedia/commons/0/0a/The_Sun_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"성공과 활력, 순수한 기쁨과 긍정",advice:"자신 있게 나서면 원하는 것을 이룰 수 있는 좋은 시기입니다.",luck:5},
    {name:"심판 (Judgement)",img:"https://upload.wikimedia.org/wikipedia/commons/2/2e/Judgement_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"각성과 재평가, 새로운 부름에 응답하기",advice:"과거를 정리하고 새로운 기회에 응답할 준비를 하세요.",luck:4},
    {name:"세계 (The World)",img:"https://upload.wikimedia.org/wikipedia/commons/9/95/The_World_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"완성과 성취, 하나의 여정의 완벽한 마무리",advice:"지금까지의 노력이 결실을 맺으며 한 단계가 완성됩니다.",luck:5},

    {name:"완드 에이스",img:"https://upload.wikimedia.org/wikipedia/commons/e/e5/Ace_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"새로운 열정과 창조적 에너지의 시작",advice:"망설이지 말고 떠오른 아이디어를 바로 시작해보세요.",luck:5},
    {name:"완드 2",img:"https://upload.wikimedia.org/wikipedia/commons/9/97/Two_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"미래를 계획하며 내딛는 첫 발걸음",advice:"큰 그림을 그리며 다음 단계를 구체적으로 계획하세요.",luck:3},
    {name:"완드 3",img:"https://upload.wikimedia.org/wikipedia/commons/3/31/Three_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"확장과 성장, 결실을 기다리는 기대감",advice:"지금까지 준비한 것들이 곧 확장되어 나갈 것입니다.",luck:4},
    {name:"완드 4",img:"https://upload.wikimedia.org/wikipedia/commons/0/0c/Four_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"축하와 안정, 화합의 순간",advice:"함께한 사람들과 이 순간을 마음껏 축하하세요.",luck:5},
    {name:"완드 5",img:"https://upload.wikimedia.org/wikipedia/commons/4/42/Five_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"경쟁과 갈등, 의견 충돌",advice:"의견 차이를 두려워하지 말고 건강한 경쟁으로 받아들이세요.",luck:2},
    {name:"완드 6",img:"https://upload.wikimedia.org/wikipedia/commons/0/0e/Six_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"승리와 인정, 자신감 있는 성공",advice:"그동안의 노력이 인정받는 순간이니 자신감을 가지세요.",luck:5},
    {name:"완드 7",img:"https://upload.wikimedia.org/wikipedia/commons/7/7f/Seven_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"자신의 입장을 지키기 위한 도전",advice:"흔들리지 말고 지금의 입장을 끝까지 지켜내세요.",luck:3},
    {name:"완드 8",img:"https://upload.wikimedia.org/wikipedia/commons/0/0a/Eight_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"빠른 진행과 신속한 소식",advice:"일이 빠르게 진행될 테니 신속하게 대응할 준비를 하세요.",luck:4},
    {name:"완드 9",img:"https://upload.wikimedia.org/wikipedia/commons/b/b7/Nine_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"지친 상태에서도 끝까지 버티는 힘",advice:"지쳐도 조금만 더 버티면 결승선이 보입니다.",luck:3},
    {name:"완드 10",img:"https://upload.wikimedia.org/wikipedia/commons/7/7c/Ten_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"과중한 책임감, 무거운 부담",advice:"짐을 혼자 다 지려 하지 말고 일부는 나누어보세요.",luck:2},
    {name:"완드 페이지",img:"https://upload.wikimedia.org/wikipedia/commons/3/34/Page_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"열정 가득한 새로운 소식과 탐구심",advice:"호기심을 갖고 배우기 시작하면 좋은 소식이 따라옵니다.",luck:4},
    {name:"완드 기사",img:"https://upload.wikimedia.org/wikipedia/commons/2/2a/Knight_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"충동적이고 과감한 행동, 모험을 향한 질주",advice:"계획보다 행동이 먼저인 시기이니 과감하게 움직이세요.",luck:3},
    {name:"완드 퀸",img:"https://upload.wikimedia.org/wikipedia/commons/8/8b/Queen_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"자신감 있고 매력적인 리더십",advice:"자신감을 갖고 스스로를 드러내면 사람들이 따를 것입니다.",luck:5},
    {name:"완드 킹",img:"https://upload.wikimedia.org/wikipedia/commons/e/e1/King_of_Wands_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"대담한 비전과 강한 추진력",advice:"큰 비전을 갖고 팀을 이끌면 성과로 이어집니다.",luck:5},

    {name:"컵 에이스",img:"https://upload.wikimedia.org/wikipedia/commons/8/86/Ace_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"새로운 사랑과 감정의 시작",advice:"마음을 열면 새로운 감정적 유대가 시작됩니다.",luck:5},
    {name:"컵 2",img:"https://upload.wikimedia.org/wikipedia/commons/7/7b/Two_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"서로를 향한 이해와 파트너십",advice:"진심으로 다가가면 관계가 더욱 깊어질 것입니다.",luck:5},
    {name:"컵 3",img:"https://upload.wikimedia.org/wikipedia/commons/9/9e/Three_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"우정과 함께 나누는 축하",advice:"주변 사람들과 기쁨을 나누면 즐거움이 배가됩니다.",luck:5},
    {name:"컵 4",img:"https://upload.wikimedia.org/wikipedia/commons/c/cd/Four_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"무기력과 권태, 놓치고 있는 기회",advice:"지금 앞에 있는 기회를 놓치지 말고 다시 살펴보세요.",luck:2},
    {name:"컵 5",img:"https://upload.wikimedia.org/wikipedia/commons/3/34/Five_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"상실에 대한 슬픔, 아직 남은 희망",advice:"잃은 것에 머물지 말고 아직 남은 것에 시선을 돌리세요.",luck:2},
    {name:"컵 6",img:"https://upload.wikimedia.org/wikipedia/commons/f/f7/Six_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"추억과 그리움, 순수했던 시절",advice:"좋았던 기억에서 힘을 얻어 지금을 따뜻하게 채워보세요.",luck:3},
    {name:"컵 7",img:"https://upload.wikimedia.org/wikipedia/commons/5/5e/Seven_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"여러 선택지 앞에서의 환상과 고민",advice:"환상에 빠지지 말고 현실적인 선택 하나에 집중하세요.",luck:3},
    {name:"컵 8",img:"https://upload.wikimedia.org/wikipedia/commons/0/0b/Eight_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"만족스럽지 않은 것을 떠나 새로운 의미를 찾아 떠남",advice:"만족스럽지 않다면 미련 없이 떠나 다른 길을 찾아도 됩니다.",luck:3},
    {name:"컵 9",img:"https://upload.wikimedia.org/wikipedia/commons/8/86/Nine_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"소원 성취, 만족스러운 행복",advice:"지금의 만족감을 충분히 누려도 좋은 때입니다.",luck:5},
    {name:"컵 10",img:"https://upload.wikimedia.org/wikipedia/commons/9/9c/Ten_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"진정한 행복과 화목한 가정",advice:"가족, 사람들과의 화목이 진정한 행복을 가져다줍니다.",luck:5},
    {name:"컵 페이지",img:"https://upload.wikimedia.org/wikipedia/commons/5/5e/Page_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"감수성 풍부한 메시지와 새로운 감정",advice:"순수한 마음으로 다가온 감정을 편하게 받아들이세요.",luck:4},
    {name:"컵 기사",img:"https://upload.wikimedia.org/wikipedia/commons/1/16/Knight_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"로맨틱한 제안과 낭만적인 접근",advice:"진심 어린 제안이나 고백을 해도 좋은 시기입니다.",luck:5},
    {name:"컵 퀸",img:"https://upload.wikimedia.org/wikipedia/commons/a/a4/Queen_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"공감 능력이 뛰어난 다정한 마음",advice:"다른 사람의 감정을 먼저 헤아리면 신뢰를 얻습니다.",luck:5},
    {name:"컵 킹",img:"https://upload.wikimedia.org/wikipedia/commons/4/4e/King_of_Cups_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"감정을 지혜롭게 다스리는 성숙함",advice:"감정에 휘둘리지 않고 침착하게 대응하면 관계가 안정됩니다.",luck:5},

    {name:"소드 에이스",img:"https://upload.wikimedia.org/wikipedia/commons/f/fd/One_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"명료한 진실과 새로운 통찰",advice:"명확한 사실을 바탕으로 결단을 내리세요.",luck:4},
    {name:"소드 2",img:"https://upload.wikimedia.org/wikipedia/commons/7/7d/Two_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"결정을 미루고 있는 교착 상태",advice:"더 이상 미루지 말고 눈을 뜨고 결정을 내려야 합니다.",luck:2},
    {name:"소드 3",img:"https://upload.wikimedia.org/wikipedia/commons/9/9f/Three_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"마음의 상처와 이별의 아픔",advice:"아픈 감정을 마주해야 비로소 치유가 시작됩니다.",luck:1},
    {name:"소드 4",img:"https://upload.wikimedia.org/wikipedia/commons/6/61/Four_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"휴식과 회복이 필요한 시간",advice:"지금은 무리하지 말고 충분히 쉬며 재정비하세요.",luck:3},
    {name:"소드 5",img:"https://upload.wikimedia.org/wikipedia/commons/4/42/Five_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"갈등에서의 씁쓸한 승리",advice:"이기더라도 잃는 것이 있을 수 있으니 무리한 다툼은 피하세요.",luck:2},
    {name:"소드 6",img:"https://upload.wikimedia.org/wikipedia/commons/f/f4/Six_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"어려움을 뒤로하고 나아가는 이동",advice:"힘들었던 상황에서 벗어나 더 나은 곳으로 나아가세요.",luck:3},
    {name:"소드 7",img:"https://upload.wikimedia.org/wikipedia/commons/0/04/Seven_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"은밀한 전략, 혹은 회피",advice:"정면 대응보다 전략적으로 접근하는 것이 유리합니다.",luck:2},
    {name:"소드 8",img:"https://upload.wikimedia.org/wikipedia/commons/b/be/Eight_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"스스로 만든 제약 속의 무력감",advice:"스스로 만든 제한을 깨달으면 생각보다 쉽게 벗어날 수 있습니다.",luck:2},
    {name:"소드 9",img:"https://upload.wikimedia.org/wikipedia/commons/1/1f/Nine_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"걱정과 불안으로 잠 못 이루는 밤",advice:"걱정은 대부분 현실보다 부풀려져 있으니 너무 불안해하지 마세요.",luck:1},
    {name:"소드 10",img:"https://upload.wikimedia.org/wikipedia/commons/6/62/Ten_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"바닥까지 간 고통, 그러나 끝난 뒤의 해방",advice:"가장 힘든 순간은 지나갔으니 이제 회복만 남았습니다.",luck:2},
    {name:"소드 페이지",img:"https://upload.wikimedia.org/wikipedia/commons/e/ef/Page_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"예리한 호기심과 새로운 정보",advice:"성급한 판단 전에 정보를 더 모아보세요.",luck:3},
    {name:"소드 기사",img:"https://upload.wikimedia.org/wikipedia/commons/f/f1/Knight_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"신속하고 단호한 행동, 직설적인 태도",advice:"목표가 분명하다면 지금 바로 밀어붙이세요.",luck:3},
    {name:"소드 퀸",img:"https://upload.wikimedia.org/wikipedia/commons/b/b1/Queen_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"명확한 판단력과 냉철한 독립심",advice:"감정을 배제하고 명확하게 판단하면 실수가 줄어듭니다.",luck:4},
    {name:"소드 킹",img:"https://upload.wikimedia.org/wikipedia/commons/8/85/King_of_Swords_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"논리와 원칙에 따른 공정한 권위",advice:"원칙과 논리로 접근하면 공정한 결론에 이릅니다.",luck:4},

    {name:"펜타클 에이스",img:"https://upload.wikimedia.org/wikipedia/commons/5/54/One_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"새로운 기회와 물질적 시작",advice:"눈앞의 기회를 구체적인 계획으로 만들어보세요.",luck:5},
    {name:"펜타클 2",img:"https://upload.wikimedia.org/wikipedia/commons/1/14/Two_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"균형을 맞추며 여러 일을 조율함",advice:"우선순위를 정하고 유연하게 조율하면 무리 없이 해낼 수 있습니다.",luck:3},
    {name:"펜타클 3",img:"https://upload.wikimedia.org/wikipedia/commons/e/ea/Three_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"협업을 통한 견고한 성과",advice:"혼자보다 함께할 때 더 좋은 결과를 만들 수 있습니다.",luck:4},
    {name:"펜타클 4",img:"https://upload.wikimedia.org/wikipedia/commons/c/c9/Four_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"안정에 대한 집착, 소유욕",advice:"쥐고 있는 것을 지키는 것도 좋지만 가끔은 나눠보세요.",luck:3},
    {name:"펜타클 5",img:"https://upload.wikimedia.org/wikipedia/commons/e/e7/Five_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"경제적 어려움과 소외감",advice:"지금은 힘들어도 도움을 청하면 상황이 나아집니다.",luck:1},
    {name:"펜타클 6",img:"https://upload.wikimedia.org/wikipedia/commons/c/cf/Six_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"나눔과 베풂, 공정한 주고받음",advice:"받은 만큼 베풀면 관계와 상황이 더 좋아집니다.",luck:5},
    {name:"펜타클 7",img:"https://upload.wikimedia.org/wikipedia/commons/1/10/Seven_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"결실을 기다리는 인내의 시간",advice:"조급해하지 말고 결실이 맺힐 때까지 꾸준히 기다리세요.",luck:3},
    {name:"펜타클 8",img:"https://upload.wikimedia.org/wikipedia/commons/4/45/Eight_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"성실한 노력과 꾸준한 숙련",advice:"작은 숙련이 쌓여 큰 실력이 되니 지금의 노력을 이어가세요.",luck:4},
    {name:"펜타클 9",img:"https://upload.wikimedia.org/wikipedia/commons/5/55/Nine_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"스스로 일군 풍요와 독립적인 안정",advice:"그동안 쌓아온 것들을 편안하게 누려도 좋습니다.",luck:5},
    {name:"펜타클 10",img:"https://upload.wikimedia.org/wikipedia/commons/f/f3/Ten_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"대대로 이어지는 풍요와 안정된 유산",advice:"장기적인 안정을 위해 기반을 단단히 다져두세요.",luck:5},
    {name:"펜타클 페이지",img:"https://upload.wikimedia.org/wikipedia/commons/8/86/Page_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"배움에 대한 열의와 실용적인 계획",advice:"새로운 것을 배우려는 마음이 곧 기회로 이어집니다.",luck:4},
    {name:"펜타클 기사",img:"https://upload.wikimedia.org/wikipedia/commons/d/d8/Knight_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"꾸준하고 신중한 진행",advice:"서두르지 말고 한 걸음씩 꾸준히 나아가세요.",luck:3},
    {name:"펜타클 퀸",img:"https://upload.wikimedia.org/wikipedia/commons/1/1d/Queen_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"현실적이고 따뜻한 살림꾼의 지혜",advice:"현실적인 감각으로 주변을 챙기면 안정이 따라옵니다.",luck:5},
    {name:"펜타클 킹",img:"https://upload.wikimedia.org/wikipedia/commons/a/a5/King_of_Pentacles_%28Rider-Waite_Smith_tarot_deck%29.png",meaning:"노력으로 이룬 물질적 성공과 여유",advice:"그동안의 노력이 물질적인 성과로 돌아올 것입니다.",luck:5}

];
